from benchmarkstt.input.core import PlainText
from benchmarkstt.schema import Word, Schema

candide = '''
"There is a concatenation of events in this best of all possible worlds:
for if you had not been kicked out of a magnificent castle for love of
Miss Cunegonde: if you had not been put into the Inquisition: if you had
not walked over America: if you had not stabbed the Baron: if you had
not lost all your sheep from the fine country of El Dorado: you would
not be here eating preserved citrons and pistachio-nuts."

"All that is very well," answered Candide, "but let us cultivate our
garden."
'''

candide_schema = [Word({"item": "\"There", "type": "word", "@raw": "\n\"There "}),
                  Word({"item": "is", "type": "word", "@raw": "is "}),
                  Word({"item": "a", "type": "word", "@raw": "a "}),
                  Word({"item": "concatenation", "type": "word", "@raw": "concatenation "}),
                  Word({"item": "of", "type": "word", "@raw": "of "}),
                  Word({"item": "events", "type": "word", "@raw": "events "}),
                  Word({"item": "in", "type": "word", "@raw": "in "}),
                  Word({"item": "this", "type": "word", "@raw": "this "}),
                  Word({"item": "best", "type": "word", "@raw": "best "}),
                  Word({"item": "of", "type": "word", "@raw": "of "}),
                  Word({"item": "all", "type": "word", "@raw": "all "}),
                  Word({"item": "possible", "type": "word", "@raw": "possible "}),
                  Word({"item": "worlds:", "type": "word", "@raw": "worlds:\n"}),
                  Word({"item": "for", "type": "word", "@raw": "for "}),
                  Word({"item": "if", "type": "word", "@raw": "if "}),
                  Word({"item": "you", "type": "word", "@raw": "you "}),
                  Word({"item": "had", "type": "word", "@raw": "had "}),
                  Word({"item": "not", "type": "word", "@raw": "not "}),
                  Word({"item": "been", "type": "word", "@raw": "been "}),
                  Word({"item": "kicked", "type": "word", "@raw": "kicked "}),
                  Word({"item": "out", "type": "word", "@raw": "out "}),
                  Word({"item": "of", "type": "word", "@raw": "of "}),
                  Word({"item": "a", "type": "word", "@raw": "a "}),
                  Word({"item": "magnificent", "type": "word", "@raw": "magnificent "}),
                  Word({"item": "castle", "type": "word", "@raw": "castle "}),
                  Word({"item": "for", "type": "word", "@raw": "for "}),
                  Word({"item": "love", "type": "word", "@raw": "love "}),
                  Word({"item": "of", "type": "word", "@raw": "of\n"}),
                  Word({"item": "Miss", "type": "word", "@raw": "Miss "}),
                  Word({"item": "Cunegonde:", "type": "word", "@raw": "Cunegonde: "}),
                  Word({"item": "if", "type": "word", "@raw": "if "}),
                  Word({"item": "you", "type": "word", "@raw": "you "}),
                  Word({"item": "had", "type": "word", "@raw": "had "}),
                  Word({"item": "not", "type": "word", "@raw": "not "}),
                  Word({"item": "been", "type": "word", "@raw": "been "}),
                  Word({"item": "put", "type": "word", "@raw": "put "}),
                  Word({"item": "into", "type": "word", "@raw": "into "}),
                  Word({"item": "the", "type": "word", "@raw": "the "}),
                  Word({"item": "Inquisition:", "type": "word", "@raw": "Inquisition: "}),
                  Word({"item": "if", "type": "word", "@raw": "if "}),
                  Word({"item": "you", "type": "word", "@raw": "you "}),
                  Word({"item": "had", "type": "word", "@raw": "had\n"}),
                  Word({"item": "not", "type": "word", "@raw": "not "}),
                  Word({"item": "walked", "type": "word", "@raw": "walked "}),
                  Word({"item": "over", "type": "word", "@raw": "over "}),
                  Word({"item": "America:", "type": "word", "@raw": "America: "}),
                  Word({"item": "if", "type": "word", "@raw": "if "}),
                  Word({"item": "you", "type": "word", "@raw": "you "}),
                  Word({"item": "had", "type": "word", "@raw": "had "}),
                  Word({"item": "not", "type": "word", "@raw": "not "}),
                  Word({"item": "stabbed", "type": "word", "@raw": "stabbed "}),
                  Word({"item": "the", "type": "word", "@raw": "the "}),
                  Word({"item": "Baron:", "type": "word", "@raw": "Baron: "}),
                  Word({"item": "if", "type": "word", "@raw": "if "}),
                  Word({"item": "you", "type": "word", "@raw": "you "}),
                  Word({"item": "had", "type": "word", "@raw": "had\n"}),
                  Word({"item": "not", "type": "word", "@raw": "not "}),
                  Word({"item": "lost", "type": "word", "@raw": "lost "}),
                  Word({"item": "all", "type": "word", "@raw": "all "}),
                  Word({"item": "your", "type": "word", "@raw": "your "}),
                  Word({"item": "sheep", "type": "word", "@raw": "sheep "}),
                  Word({"item": "from", "type": "word", "@raw": "from "}),
                  Word({"item": "the", "type": "word", "@raw": "the "}),
                  Word({"item": "fine", "type": "word", "@raw": "fine "}),
                  Word({"item": "country", "type": "word", "@raw": "country "}),
                  Word({"item": "of", "type": "word", "@raw": "of "}),
                  Word({"item": "El", "type": "word", "@raw": "El "}),
                  Word({"item": "Dorado:", "type": "word", "@raw": "Dorado: "}),
                  Word({"item": "you", "type": "word", "@raw": "you "}),
                  Word({"item": "would", "type": "word", "@raw": "would\n"}),
                  Word({"item": "not", "type": "word", "@raw": "not "}),
                  Word({"item": "be", "type": "word", "@raw": "be "}),
                  Word({"item": "here", "type": "word", "@raw": "here "}),
                  Word({"item": "eating", "type": "word", "@raw": "eating "}),
                  Word({"item": "preserved", "type": "word", "@raw": "preserved "}),
                  Word({"item": "citrons", "type": "word", "@raw": "citrons "}),
                  Word({"item": "and", "type": "word", "@raw": "and "}),
                  Word({"item": "pistachio-nuts.\"", "type": "word", "@raw": "pistachio-nuts.\"\n\n"}),
                  Word({"item": "\"All", "type": "word", "@raw": "\"All "}),
                  Word({"item": "that", "type": "word", "@raw": "that "}),
                  Word({"item": "is", "type": "word", "@raw": "is "}),
                  Word({"item": "very", "type": "word", "@raw": "very "}),
                  Word({"item": "well,\"", "type": "word", "@raw": "well,\" "}),
                  Word({"item": "answered", "type": "word", "@raw": "answered "}),
                  Word({"item": "Candide,", "type": "word", "@raw": "Candide, "}),
                  Word({"item": "\"but", "type": "word", "@raw": "\"but "}),
                  Word({"item": "let", "type": "word", "@raw": "let "}),
                  Word({"item": "us", "type": "word", "@raw": "us "}),
                  Word({"item": "cultivate", "type": "word", "@raw": "cultivate "}),
                  Word({"item": "our", "type": "word", "@raw": "our\n"}),
                  Word({"item": "garden.\"", "type": "word", "@raw": "garden.\"\n"})]


def test_plaintext():
    assert list(PlainText(candide)) == candide_schema
    assert Schema(PlainText(candide)) == candide_schema
