@startuml

skinparam packageStyle Frame
!define LIGHTORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
package benchmarkstt.input [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.html#]] {

	class benchmarkstt.input.Base  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.html#benchmarkstt.input.Base]] {
		.. Public Methods ..
		+__iter__()
	}
}

package benchmarkstt.input.core [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.core.html#]] {

	class benchmarkstt.input.core.File  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.core.html#benchmarkstt.input.core.File]] extends benchmarkstt.input.Base {
		.. Public Methods ..
		+__init__(file, input_type=None, normalizer=None)
		+__iter__()
		.. Static Methods ..
		{static} +available_types()
	}

	class benchmarkstt.input.core.PlainText  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.core.html#benchmarkstt.input.core.PlainText]] extends benchmarkstt.input.Base {
		.. Public Methods ..
		+__init__(text, segmenter=None, normalizer=None)
		+__iter__()
	}
}




@enduml