@startuml

title benchmarkstt.input

skinparam packageStyle Frame
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu
package benchmarkstt.input {

	class benchmarkstt.input.Base [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.html#benchmarkstt.input.Base]] {
		.. Public Methods ..
		+__iter__()
	}


}

package benchmarkstt.input.core {

	class benchmarkstt.input.core.File [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.core.html#benchmarkstt.input.core.File]] {
		.. Public Methods ..
		+__init__(file, input_type=None, normalizer=None)
		+__iter__()
		.. Static Methods ..
		{static} +available_types()
	}


	class benchmarkstt.input.core.PlainText [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.core.html#benchmarkstt.input.core.PlainText]] {
		.. Public Methods ..
		+__init__(text, segmenter=None, normalizer=None)
		+__iter__()
	}

}


benchmarkstt.input.core.File -up-|> benchmarkstt.input.Base
benchmarkstt.input.core.PlainText -up-|> benchmarkstt.input.Base

@enduml