@startuml

title benchmarkstt.metrics

skinparam packageStyle Frame
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu
package benchmarkstt.metrics {

	class benchmarkstt.metrics.Base [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.html#benchmarkstt.metrics.Base]] {
		.. Public Methods ..
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}



}

package benchmarkstt.metrics {



}

package benchmarkstt.metrics {



}

package benchmarkstt.metrics.core {


	class benchmarkstt.metrics.core.DiffCounts [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.DiffCounts]] {
		.. Public Methods ..
		+__init__(differ_class=None)
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}


	class benchmarkstt.metrics.core.OpcodeCounts [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.OpcodeCounts]] {
		.. Public Methods ..
		+__getnewargs__()
		+__new__(_cls, equal, replace, insert, delete)
		+__repr__()
		.. Protected Methods ..
		-_asdict()
		+_replace(**kwds)
		.. Static Methods ..
		{static} +_make(iterable)
	}




	class benchmarkstt.metrics.core.WER [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.WER]] {
		.. Public Methods ..
		+__init__(mode=None, differ_class=None)
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}


	class benchmarkstt.metrics.core.WordDiffs [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.WordDiffs]] {
		.. Public Methods ..
		+__init__(dialect=None, differ_class=None)
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}

}


benchmarkstt.metrics.core.DiffCounts -up-|> benchmarkstt.metrics.Base
benchmarkstt.metrics.core.WER -up-|> benchmarkstt.metrics.Base
benchmarkstt.metrics.core.WordDiffs -up-|> benchmarkstt.metrics.Base

@enduml