@startuml

title benchmarkstt.api

skinparam packageStyle Frame
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu
package benchmarkstt.api {
}

package benchmarkstt.api {
}

package benchmarkstt.api.jsonrpc {

	class benchmarkstt.api.jsonrpc.DefaultMethods [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.api.jsonrpc.html#benchmarkstt.api.jsonrpc.DefaultMethods]] {
		.. Public Methods ..
		+help(methods)
		+version()
	}


	class benchmarkstt.api.jsonrpc.MagicMethods [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.api.jsonrpc.html#benchmarkstt.api.jsonrpc.MagicMethods]] {
		.. Public Methods ..
		+__init__()
		+is_safe_path(path)
		+load(name, module)
		+register(name, callback)
		+serve(config, callback)
	}




	class benchmarkstt.api.jsonrpc.SecurityError [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.api.jsonrpc.html#benchmarkstt.api.jsonrpc.SecurityError]] {
	}


}

package benchmarkstt.api.gunicorn {
}




@enduml