@startuml

title benchmarkstt.segmentation

skinparam packageStyle Frame
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu
package benchmarkstt.segmentation {

	class benchmarkstt.segmentation.Base [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.segmentation.html#benchmarkstt.segmentation.Base]] {
		.. Public Methods ..
		+__iter__()
	}


}

package benchmarkstt.segmentation.core {



	class benchmarkstt.segmentation.core.Simple [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.segmentation.core.html#benchmarkstt.segmentation.core.Simple]] {
		.. Public Methods ..
		+__init__(text: str, pattern='[\\n\\t\\s]+', normalizer=None)
		+__iter__()
	}

}


benchmarkstt.segmentation.core.Simple -up-|> benchmarkstt.segmentation.Base

@enduml