@startuml
title Benchmarkstt.output


class benchmarkstt.output.Base [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.html#benchmarkstt.output.Base]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+result(self, title, result)
}

class benchmarkstt.output.core.Json [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.Json]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self)
	+result(self, title, result)
}

class benchmarkstt.output.core.MarkDown [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.MarkDown]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+print(self, result)
	+result(self, title, result)
}

class benchmarkstt.output.core.ReStructuredText [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.ReStructuredText]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+print(self, result)
	+result(self, title, result)
}

class benchmarkstt.output.core.SimpleTextBase [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.SimpleTextBase]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+print(self, result)
	+result(self, title, result)
}

benchmarkstt.output.core.Json ----|> benchmarkstt.output.Base
benchmarkstt.output.core.MarkDown ----|> benchmarkstt.output.core.SimpleTextBase
benchmarkstt.output.core.ReStructuredText ----|> benchmarkstt.output.core.SimpleTextBase
benchmarkstt.output.core.SimpleTextBase ----|> benchmarkstt.output.Base
@enduml