@startuml

skinparam packageStyle Frame
package benchmarkstt.output [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.html#]] {

	class benchmarkstt.output.Base << ContextManager >>  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.html#benchmarkstt.output.Base]] {
		.. Public Methods ..
		+result(title, result)
	}
}

package benchmarkstt.output.core [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#]] {

	class benchmarkstt.output.core.Json << ContextManager >>  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.Json]] extends benchmarkstt.output.Base {
		.. Public Methods ..
		+__init__()
		+result(title, result)
	}

	class benchmarkstt.output.core.MarkDown << ContextManager >>  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.MarkDown]] extends benchmarkstt.output.core.SimpleTextBase {
		.. Public Methods ..
		+print(result)
		+result(title, result)
	}

	class benchmarkstt.output.core.ReStructuredText << ContextManager >>  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.ReStructuredText]] extends benchmarkstt.output.core.SimpleTextBase {
		.. Public Methods ..
		+print(result)
		+result(title, result)
	}

	class benchmarkstt.output.core.SimpleTextBase << ContextManager >>  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.SimpleTextBase]] extends benchmarkstt.output.Base {
		.. Public Methods ..
		+print(result)
		+result(title, result)
	}
}




@enduml