@startuml
title benchmarkstt.diff

package benchmarkstt.diff.formatter {

	class benchmarkstt.diff.formatter.CLIDiffDialect [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.CLIDiffDialect]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self, show_color_key=None)
	+output(self)
	+preprocessor(txt)
	}

	class benchmarkstt.diff.formatter.Dialect [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.Dialect]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self)
	+output(self)
	}

	class benchmarkstt.diff.formatter.DiffFormatter [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.DiffFormatter]] {
	+__init__(self, dialect=None, *args, **kwargs)
	+diff(self, a, b, opcodes=None, preprocessor=None)
	{static} +has_dialect(dialect)
	}

	class benchmarkstt.diff.formatter.HTMLDiffDialect [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.HTMLDiffDialect]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self)
	+output(self)
	+preprocessor(txt)
	}

	class benchmarkstt.diff.formatter.JSONDiffDialect [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.JSONDiffDialect]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self)
	-_format(self, kind, txt, txt2=None)
	+delete_format(self, txt)
	+equal_format(self, txt)
	+insert_format(self, txt)
	+output(self)
	+preprocessor(txt)
	+replace_format(self, a, b)
	}

	class benchmarkstt.diff.formatter.ListDialect [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.ListDialect]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self)
	-_format(self, kind, txt, txt2=None)
	+delete_format(self, txt)
	+equal_format(self, txt)
	+insert_format(self, txt)
	+output(self)
	+preprocessor(txt)
	+replace_format(self, a, b)
	}

	class benchmarkstt.diff.formatter.RestructuredTextDialect [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.RestructuredTextDialect]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self, show_color_key=None)
	+output(self)
	+preprocessor(txt)
	}

	class benchmarkstt.diff.formatter.UTF8Dialect [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.formatter.html#benchmarkstt.diff.formatter.UTF8Dialect]] {
	+__enter__(self)
	+__exit__(self, exc_type, exc_val, exc_tb)
	+__init__(self)
	+delete_format(self, txt)
	+insert_format(self, txt)
	+output(self)
	+preprocessor(txt)
	}
}
package benchmarkstt.diff {

	class benchmarkstt.diff.Base [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.html#benchmarkstt.diff.Base]] {
	+__init__(self, a='', b='')
	+get_opcodes(self)
	}
}
package benchmarkstt.diff.core {

	class benchmarkstt.diff.core.RatcliffObershelp [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.diff.core.html#benchmarkstt.diff.core.RatcliffObershelp]] {
	-_SequenceMatcher__chain_b(self)
	+__init__(self, a, b, *args, **kwargs)
	+find_longest_match(self, alo, ahi, blo, bhi)
	+get_grouped_opcodes(self, n=3)
	+get_matching_blocks(self)
	+get_opcodes(self)
	+quick_ratio(self)
	+ratio(self)
	+real_quick_ratio(self)
	+set_seq1(self, a)
	+set_seq2(self, b)
	+set_seqs(self, a, b)
	}
}

benchmarkstt.diff.formatter.CLIDiffDialect ----|> benchmarkstt.diff.formatter.Dialect
benchmarkstt.diff.formatter.HTMLDiffDialect ----|> benchmarkstt.diff.formatter.Dialect
benchmarkstt.diff.formatter.JSONDiffDialect ----|> benchmarkstt.diff.formatter.ListDialect
benchmarkstt.diff.formatter.ListDialect ----|> benchmarkstt.diff.formatter.Dialect
benchmarkstt.diff.formatter.RestructuredTextDialect ----|> benchmarkstt.diff.formatter.CLIDiffDialect
benchmarkstt.diff.formatter.UTF8Dialect ----|> benchmarkstt.diff.formatter.Dialect
benchmarkstt.diff.core.RatcliffObershelp ----|> benchmarkstt.diff.Base
@enduml