@startuml

title benchmarkstt.metrics

skinparam packageStyle Frame
!define LIGHTORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
package benchmarkstt.metrics {

	class benchmarkstt.metrics.Base  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.html#benchmarkstt.metrics.Base]] {
		.. Public Methods ..
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}



}

package benchmarkstt.metrics {



}

package benchmarkstt.metrics {



}

package benchmarkstt.metrics.core {


	class benchmarkstt.metrics.core.DiffCounts  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.DiffCounts]] extends benchmarkstt.metrics.Base {
		.. Public Methods ..
		+__init__(differ_class=None)
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}


	class benchmarkstt.metrics.core.OpcodeCounts<namedtuple> << (T, yellow) >> [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.OpcodeCounts]] {
		.. Fields ..
		+equal
		+replace
		+insert
		+delete
	}




	class benchmarkstt.metrics.core.WER  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.WER]] extends benchmarkstt.metrics.Base {
		.. Public Methods ..
		+__init__(mode=None, differ_class=None)
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}


	class benchmarkstt.metrics.core.WordDiffs  [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.metrics.core.html#benchmarkstt.metrics.core.WordDiffs]] extends benchmarkstt.metrics.Base {
		.. Public Methods ..
		+__init__(dialect=None, differ_class=None)
		+compare(ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
	}

}




@enduml