@startuml

title benchmarkstt.output

skinparam packageStyle Frame
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu
package benchmarkstt.output {

	class benchmarkstt.output.Base [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.html#benchmarkstt.output.Base]] {
		.. Public Methods ..
		+__enter__()
		+__exit__(exc_type, exc_val, exc_tb)
		+result(title, result)
	}


}

package benchmarkstt.output.core {

	class benchmarkstt.output.core.Json [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.Json]] {
		.. Public Methods ..
		+__enter__()
		+__exit__(exc_type, exc_val, exc_tb)
		+__init__()
		+result(title, result)
	}


	class benchmarkstt.output.core.MarkDown [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.MarkDown]] {
		.. Public Methods ..
		+__enter__()
		+__exit__(exc_type, exc_val, exc_tb)
		+print(result)
		+result(title, result)
	}



	class benchmarkstt.output.core.ReStructuredText [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.ReStructuredText]] {
		.. Public Methods ..
		+__enter__()
		+__exit__(exc_type, exc_val, exc_tb)
		+print(result)
		+result(title, result)
	}



	class benchmarkstt.output.core.SimpleTextBase [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.output.core.html#benchmarkstt.output.core.SimpleTextBase]] {
		.. Public Methods ..
		+__enter__()
		+__exit__(exc_type, exc_val, exc_tb)
		+print(result)
		+result(title, result)
	}

}


benchmarkstt.output.core.Json -up-|> benchmarkstt.output.Base
benchmarkstt.output.core.MarkDown -up-|> benchmarkstt.output.core.SimpleTextBase
benchmarkstt.output.core.ReStructuredText -up-|> benchmarkstt.output.core.SimpleTextBase
benchmarkstt.output.core.SimpleTextBase -up-|> benchmarkstt.output.Base

@enduml