@startuml
title benchmarkstt.input

package benchmarkstt.input {

	class benchmarkstt.input.Base [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.html#benchmarkstt.input.Base]] {
	+__iter__(self)
	}
}
package benchmarkstt.input.core {

	class benchmarkstt.input.core.File [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.core.html#benchmarkstt.input.core.File]] {
	+__init__(self, file, input_type=None, normalizer=None)
	+__iter__(self)
	{static} +available_types()
	}

	class benchmarkstt.input.core.PlainText [[https://benchmarkstt.readthedocs.io/en/latest/modules/benchmarkstt.input.core.html#benchmarkstt.input.core.PlainText]] {
	+__init__(self, text, segmenter=None, normalizer=None)
	+__iter__(self)
	}
}

benchmarkstt.input.core.File ----|> benchmarkstt.input.Base
benchmarkstt.input.core.PlainText ----|> benchmarkstt.input.Base
@enduml