@startuml
title 'Metrics'
		class benchmarkstt.metrics.Base {
			+compare(self, ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
		}
		class benchmarkstt.metrics.core.DiffCounts {
			+__init__(self, differ_class=None)
			+compare(self, ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
		}
		class benchmarkstt.metrics.core.OpcodeCounts {
			+__getnewargs__(self)
			+__new__(_cls, equal, replace, insert, delete)
			+__repr__(self)
		}
		class benchmarkstt.metrics.core.WER {
			+__init__(self, mode=None, differ_class=None)
			+compare(self, ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
		}
		class benchmarkstt.metrics.core.WordDiffs {
			+__init__(self, dialect=None, differ_class=None)
			+compare(self, ref: benchmarkstt.schema.Schema, hyp: benchmarkstt.schema.Schema)
		}

benchmarkstt.metrics.core.DiffCounts --up--|> benchmarkstt.metrics.Base
benchmarkstt.metrics.core.WER --up--|> benchmarkstt.metrics.Base
benchmarkstt.metrics.core.WordDiffs --up--|> benchmarkstt.metrics.Base
@enduml