@startuml

interface NormalisationInterface 
{
  + normalise()
}

class NormalisationComposite {
  NormalisationInterface[] _children
  + add(NormalisationInterface)
}



class NormalisationLowercase {
  + normalise()
}

package RegexBased {
  class NormalisationRegex {
    __init__(regex)
    + normalise()
  }

  class NormalisationAlphaNumeric { 
    __init__('[^a-z0-9]') 
  }

  class NormalisationAlphaNumericUnicode {
    __init__(r'[^\w]')
  }
}

class NormalisationTransliterateUnicode {
  + normalise()
}

NormalisationComposite ..|> NormalisationInterface
NormalisationLowercase ..|> NormalisationInterface
NormalisationRegex ..|> NormalisationInterface
NormalisationTransliterateUnicode ..|> NormalisationInterface
NormalisationAlphaNumeric --|> NormalisationRegex
NormalisationAlphaNumericUnicode --|> NormalisationRegex
NormalisationInterface "1..*" <--* NormalisationComposite
@enduml
